#goal definition
int32 algorithm
int32 update_method
uint8 SINGLE=0
uint8 MULTI=1
uint8 KALMAN=2
uint8 UPDATE_METHOD_NORMAL=0
uint8 UPDATE_METHOD_WITH_FRAME_COUNT=1
---
#result definition
bool status
---
#feedback
bool feedback_status